"""Initial migration

Revision ID: 21a70537b1b5
Revises: 5244c423b850
Create Date: 2026-01-01 15:18:00.778921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21a70537b1b5'
down_revision: Union[str, Sequence[str], None] = '5244c423b850'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('nickname', sa.String(), nullable=True))
    op.drop_constraint(op.f('projects_project_nickname_key'), 'projects', type_='unique')
    op.drop_column('projects', 'project_nickname')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_nickname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('projects_project_nickname_key'), 'projects', ['project_nickname'], postgresql_nulls_not_distinct=False)
    op.drop_column('projects', 'nickname')
    # ### end Alembic commands ###
