"""Initial migration

Revision ID: 5244c423b850
Revises: 8c7b6f618931
Create Date: 2026-01-01 12:53:06.440953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5244c423b850'
down_revision: Union[str, Sequence[str], None] = '8c7b6f618931'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('main_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'main_image')
    # ### end Alembic commands ###
