"""Initial migration

Revision ID: 6e9459cebbfd
Revises: 9c3dd19e1d5c
Create Date: 2025-12-20 11:44:35.154729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e9459cebbfd'
down_revision: Union[str, Sequence[str], None] = '9c3dd19e1d5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_images',
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_index(op.f('ix_project_images_image_id'), 'project_images', ['image_id'], unique=False)
    op.create_table('project_image_association',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['project_images.image_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.pro_id'], ),
    sa.PrimaryKeyConstraint('project_id', 'image_id')
    )
    op.drop_column('projects', 'img')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('img', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('project_image_association')
    op.drop_index(op.f('ix_project_images_image_id'), table_name='project_images')
    op.drop_table('project_images')
    # ### end Alembic commands ###
