"""Initial migration

Revision ID: 6f6cd1b55a56
Revises: 21a70537b1b5
Create Date: 2026-01-01 22:35:40.085461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f6cd1b55a56'
down_revision: Union[str, Sequence[str], None] = '21a70537b1b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_type', sa.String(), nullable=True))
    op.drop_column('projects', 'nickname')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('nickname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('projects', 'project_type')
    # ### end Alembic commands ###
