"""Initial migration

Revision ID: 8c7b6f618931
Revises: 6e9459cebbfd
Create Date: 2026-01-01 12:33:57.226581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c7b6f618931'
down_revision: Union[str, Sequence[str], None] = '6e9459cebbfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_nickname', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'projects', ['project_nickname'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_column('projects', 'project_nickname')
    # ### end Alembic commands ###
