"""Initial migration

Revision ID: 9c3dd19e1d5c
Revises: 
Create Date: 2025-11-11 22:05:21.084601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c3dd19e1d5c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('my_roll',
    sa.Column('roll_id', sa.Integer(), nullable=False),
    sa.Column('roll_title', sa.String(), nullable=False),
    sa.Column('roll_topic', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('roll_id')
    )
    op.create_index(op.f('ix_my_roll_roll_id'), 'my_roll', ['roll_id'], unique=False)
    op.create_table('req_skills',
    sa.Column('req_skill_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('frameworks', sa.String(), nullable=True),
    sa.Column('tools', sa.String(), nullable=True),
    sa.Column('database', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('req_skill_id')
    )
    op.create_index(op.f('ix_req_skills_database'), 'req_skills', ['database'], unique=False)
    op.create_index(op.f('ix_req_skills_frameworks'), 'req_skills', ['frameworks'], unique=False)
    op.create_index(op.f('ix_req_skills_language'), 'req_skills', ['language'], unique=False)
    op.create_index(op.f('ix_req_skills_req_skill_id'), 'req_skills', ['req_skill_id'], unique=False)
    op.create_index(op.f('ix_req_skills_tools'), 'req_skills', ['tools'], unique=False)
    op.create_table('projects',
    sa.Column('pro_id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('description', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('my_roll_id', sa.Integer(), nullable=False),
    sa.Column('req_skill_id', sa.Integer(), nullable=False),
    sa.Column('key_achievement', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('img', sa.String(), nullable=True),
    sa.Column('logo_img', sa.String(), nullable=True),
    sa.Column('project_video', sa.String(), nullable=True),
    sa.Column('github_link', sa.String(), nullable=True),
    sa.Column('website_link', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['my_roll_id'], ['my_roll.roll_id'], ),
    sa.ForeignKeyConstraint(['req_skill_id'], ['req_skills.req_skill_id'], ),
    sa.PrimaryKeyConstraint('pro_id'),
    sa.UniqueConstraint('project_name'),
    sa.UniqueConstraint('req_skill_id')
    )
    op.create_index(op.f('ix_projects_pro_id'), 'projects', ['pro_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_pro_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_req_skills_tools'), table_name='req_skills')
    op.drop_index(op.f('ix_req_skills_req_skill_id'), table_name='req_skills')
    op.drop_index(op.f('ix_req_skills_language'), table_name='req_skills')
    op.drop_index(op.f('ix_req_skills_frameworks'), table_name='req_skills')
    op.drop_index(op.f('ix_req_skills_database'), table_name='req_skills')
    op.drop_table('req_skills')
    op.drop_index(op.f('ix_my_roll_roll_id'), table_name='my_roll')
    op.drop_table('my_roll')
    # ### end Alembic commands ###
